name: js-bump-version

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  js-bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Update version, commit, and create tag
        working-directory: ts
        run: |
          npm version ${{ github.event.inputs.release_type }} --no-git-tag-version
          echo version="$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: bump @maplibre/mlt version to ${{ env.version }}
          branch: mlt-js-version-${{ env.version }}
          title: bump @maplibre/mlt version to ${{ env.version }}
