name: release-js-create-tag

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  release-js-create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: ./.github/actions/mlt-setup-node

      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin git@github.com:${{ github.repository }}.git

      - name: Update version, commit, and create tag
        working-directory: ts
        run: |
          npm version ${{ github.event.inputs.release_type }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          git add package.json package-lock.json
          git commit -m "chore: bump MLT JS version to ${VERSION}"
          git tag -a "js-v${VERSION}" -m "Release js-v${VERSION}"
          git push origin HEAD:main
          git push origin "js-v${VERSION}"
