name: Release MLT JavaScript

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-check:
    name: Check if version changed
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@5102328418c0130d66ca712d755c303e93368ce2
        with:
          file-name: ts/package.json

    outputs:
      publish: ${{ steps.check.outputs.changed }}

  release:
    name: Release
    needs: release-check
    if: ${{ needs.release-check.outputs.publish == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ts
    permissions:
      contents: write         # allow making a release
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/mlt-setup-node

      - name: Get version
        run: |
          version="$(node -p "require('./package.json').version")"
          echo version="$version" >> "$GITHUB_ENV"
          if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo prerelease=false >> "$GITHUB_ENV"
          else
            echo prerelease=true >> "$GITHUB_ENV"
          fi

      - name: Install
        run: npm ci

      - name: Build
        run: |
          npm run build

      - name: Release (GitHub) - Create Draft
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          name: js-v${{ env.version }}
          tag_name: js-v${{ env.version }}
          prerelease: ${{ env.prerelease }}
          draft: true

      - name: Publish npm package
        run: |
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}

      - name: Publish GitHub release (remove draft)
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          tag_name: js-v${{ env.version }}
          name: js-v${{ env.version }}
          draft: false
